### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by ramchalamkr** [hongzimao/a3c#2]
I am trying to implement A3C for a particular problem.
With some tweaking, I have got it working for my specific problem. 
I do have a few queries regarding the optimisation though.

1.The actor and Critic are to be optimised simultaneously right? Although it does seem like they are being optimised simultaneously, they both have totally separate models. Could you throw some light on that specific implementation?
2. In some cases of higher difficulty of my problem, the tdloss seems to have converged to 0, but the expected reward is still some way off the actual expected rewards and doesn't seem to converge completely. Do you know why that could be happening? 
3. One thing I did notice in the implementation is that while training if the episode doesn't reach the done state within the train_Batch_length, it stops after that and trains it till the size with done state as false. This seems to work really good when my state space is quite small. But for Larger state spaces, it becomes really tricky to tweak this exact training batch size. 

Thanks!

**Comment by hongzimao** [comment]
1. Feel free to merge the to networks and try out empirically to see if there is any improvements. We separate them out mainly for easier evaluation and probing.

2. In that case I would expect the actual reward to also converge. Not exactly sure why the actual reward doesn’t correspond to the expected reward. One possibility is the mapping between state and total reward is stochastic in your problem (so inherently there is variation and actual reward and expected reward won’t match)

3. Our episode length for this problem is also quite small (<100), so I think it works similarly as your case when the episode length is small.

**Comment by ramchalamkr** [comment]
Thank you!
